resource "proxmox_vm_qemu" "create_nodes" {
  count            = var.number_of_instances
  name             = var.servers[count.index].name
  desc             = "server generated by [proxmox-terraform-tasks]"
  vmid             = var.servers[count.index].vmid
  target_node      = var.pve_target_node
  agent            = 1
  clone            = var.cloud_image_name
  cores            = var.servers[count.index].cpu
  sockets          = 1
  memory           = var.servers[count.index].ram
  scsihw           = "virtio-scsi-pci"
  bootdisk         = "scsi0"
  boot             = "cd"
  os_type          = "cloud-init"
  cpu              = var.cpu_type
  ciuser           = var.vm_ciuser
  cipassword       = var.vm_cipwd
  tags             = var.servers[count.index].tags
  automatic_reboot = false
  ipconfig0        = var.servers[count.index].ipconfig0
  onboot           = var.servers[count.index].startup_onboot
  startup          = var.servers[count.index].startup_attributes
  nameserver       = var.nameserver
  searchdomain     = var.searchdomain

  network {
    bridge  = var.bridge_network_name
    model   = "virtio"
    macaddr = var.servers[count.index].macaddr
  }

  /*
  Comment the disk section because of the incompatibility between proxmox 8.1.3
  and  "telmate/proxmox"
  [Issue Report](https://github.com/Telmate/terraform-provider-proxmox/issues/887)

  disk {
    storage = var.pve_storage_disk_name
    type    = "scsi"
    size    = var.servers[count.index].disk
    ssd     = var.servers[count.index].disk_ssd
    format  = var.servers[count.index].disk_format
    backup  = var.servers[count.index].disk_backup
  }*/
}

