resource "proxmox_vm_qemu" "create_nodes" {

  count            = var.number_of_instances
  name             = var.servers[count.index].name
  desc             = "server generated by [proxmox-terraform-tasks]"
  vmid             = var.servers[count.index].vmid
  target_node      = var.pve_target_node
  agent            = 1
  clone            = var.cloud_image_name
  cores            = var.servers[count.index].cpu
  sockets          = 1
  memory           = var.servers[count.index].ram
  scsihw           = "virtio-scsi-pci"
  os_type          = "cloud-init"
  cpu              = var.cpu_type
  ciuser           = var.vm_ciuser
  cipassword       = var.vm_cipwd
  tags             = var.servers[count.index].tags
  automatic_reboot = true

  network {
    bridge  = var.bridge_network_name
    model   = "virtio"
    macaddr = var.servers[count.index].macaddr
  }

  disk {
    storage = var.pve_storage_disk_name
    type    = "scsi"
    size    = var.servers[count.index].disk
    ssd     = var.servers[count.index].disk_ssd
    format  = var.servers[count.index].disk_format
    backup  = var.servers[count.index].disk_backup
  }

  //ipconfig0    = "ip=${var.servers[count.index].ip},gw=192.168.30.1"
  //nameserver   = "192.168.30.2"
  //searchdomain = "sp1.theworkpc.com"

}

